[FIX] Downgrade numpy version due to compatibility issues
Actual error:

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject